site_name: PyLLMut Documentation

nav:
  - Home: index.md
  - User Guide:
      - Installation: user/install.md
      - Quick Start: user/start.md
  - API Reference:
      - Mutant Generator: api/generator.md
      - ModelType (Enum): api/model_type.md
      - Mutation Report: api/mutation_report.md
      - Mutant Info: api/mutant_info.md
      - Mutant Type (Enum): api/mutant_type.md
      - Prompt Info: api/prompt_info.md
      - Response Info: api/response_info.md

repo_url: https://github.com/mohrez86/pyllmut
repo_name: mohrez86/pyllmut

#theme: readthedocs
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.sections  # Adds collapsible sub-sections in the sidebar
    - content.code.copy
    - navigation.top
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true  # Hide source code links
            show_root_heading: true  # Show the class/module heading
            show_if_no_docstring: true  # Show members even if they lack docstrings
            docstring_style: google  # Format docstrings using Google style
            show_submodules: true  # Show submodules of the package
            show_bases: true  # Show base classes of the class
            inherited_members: true  # Show inherited methods from parent classes
            members_order: alphabetical  # Order members alphabetically
            group_by_category: true  # Group members (methods, attributes)
